exp_name: base_classification
task_name: classification
num_classes: 20
dataset:
  batch: 32
  train_csv_path: ['./data/label_random/label/data_label.csv']
  val_csv_path: ['./data/label_val.csv']
  metric: 'cosine'
  image_size: 112
train:
  model: 'resnet18'
  lr: 0.0001
  epochs: 100
  val_iters: 100
  loss: {'probbasedmse':0.01, 'crossentropy':1}   # same as WeightedMSELoss
  optim: 'adamw'
  scheduler: {'MultiStepLR': {"milestones": [5, 10, 15, 20], "gamma": 0.3}}
